/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.deephacks.logbuffers.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface LogbuffersProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"LogbuffersProtocol\",\"namespace\":\"org.deephacks.logbuffers.avro\",\"types\":[{\"type\":\"record\",\"name\":\"PageView\",\"fields\":[{\"name\":\"url\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"value\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"Visit\",\"fields\":[{\"name\":\"url\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"value\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"Message\",\"fields\":[{\"name\":\"message\",\"type\":[\"PageView\",\"Visit\"],\"default\":null}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends LogbuffersProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = org.deephacks.logbuffers.avro.LogbuffersProtocol.PROTOCOL;
  }
}